#!/bin/bash

main() {
  vpnc
  if [ -z "$1" ]
  then
    while true
    do
      sleep 10
    done
  else
    local me; me=$(hostname -i)
    local host; host=$1
    shift
    echo "proxying $host on $me"
    while [ ! -z "$1" ]
    do
        socat "TCP-LISTEN:$1,fork" "TCP:$host:$1" &
        echo "port --> $1"
        shift
    done
    while true
    do
      sleep 10
    done
  fi
}

main "$@"
