#!/bin/bash

main() {
  vpnc
  if [ -z "$1" ]
  then
    while true
    do
      sleep 10
    done
  else
    local me; me=$(hostname -i)
    local host; host=$(echo "$1" | cut -d ":" -f 1)
    shift
    echo "proxying $host on $me"
    for port in "$@"
    do
        socat "TCP-LISTEN:$port,fork" "TCP:$host:$port" &
        echo "port --> $port" &
    done
    while true
    do
      sleep 10
    done
  fi
}

main "$@"
