#!/bin/bash

main() {
  [ -z "$1" ] && echo missing env name && return 1
  local ENV=$1
  shift
  docker run \
    -d --privileged=true \
    --name="$ENV-vpn" \
    -v "$(pwd)/$ENV/vpnc:/etc/vpnc:ro" \
    -v "$(pwd)/$ENV/workspace:/root/workspace:ro" \
    coog/vpn "$@"
}

main "$@"
