#!/bin/bash

main() {
  [ -z "$1" ] && echo missing env name && return 1
  docker run \
    -d --privileged=true \
    --name="$1-vpn" \
    -v "$(pwd)/$1/vpnc:/etc/vpnc:ro" \
    -v "$(pwd)/$1/workspace:/root/workspace:ro" \
    coog/vpn "$2"
}

main "$@"
